# Generated by Django 2.1.5 on 2019-01-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_pizzas', '0002_auto_20190122_0646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'Toppings'},
        ),
    ]
