# Generated by Django 2.1.5 on 2019-01-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_pizzas', '0004_pizza_pizza_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_size',
            new_name='Pizza_Size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='Pizza_Flavor',
            field=models.CharField(choices=[('PR', 'Pepperonia'), ('CF', 'Canadian Flavor'), ('FS', 'Four Season')], default='CF', max_length=2),
        ),
        migrations.AddField(
            model_name='toppings',
            name='Topping_Choice',
            field=models.CharField(choices=[('A', 'Apple'), ('O', 'Orange'), ('I', 'IceCream')], default='A', max_length=1),
        ),
    ]
